# Generated by Django 3.2.9 on 2021-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mag_edit_page',
            name='image',
            field=models.ImageField(upload_to='magazine'),
        ),
        migrations.AlterField(
            model_name='mag_edition',
            name='summary_title',
            field=models.ImageField(upload_to='magazine'),
        ),
        migrations.AlterField(
            model_name='mag_edition',
            name='thumb_firstpage',
            field=models.ImageField(upload_to='magazine'),
        ),
        migrations.AlterField(
            model_name='mag_edition',
            name='thumb_secondthird',
            field=models.ImageField(upload_to='magazine'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='thumb_firstpage',
            field=models.ImageField(upload_to='magazine'),
        ),
    ]
