# Generated by Django 3.2.9 on 2021-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0002_auto_20211110_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mag_edition',
            name='summary_title',
            field=models.CharField(max_length=200),
        ),
    ]
